import { readFile } from 'node:fs/promises';
import { performance } from 'node:perf_hooks';

const TEST_REF='gontnlfmothfglssbyyk',PROD_REF='lwzsxuaqqeoamukduhev';
const RUNS=Number(process.env.PHASE4_RUNS||5);
const app=await readFile(new URL('../app.js',import.meta.url),'utf8');
const literal=n=>{const m=app.match(new RegExp("const\\s+"+n+"\\s*=\\s*'([^']+)'"));if(!m)throw Error('Configuração ausente: '+n);return m[1];};
const SB_URL=process.env.SUPABASE_TEST_URL||literal('SB_TESTE_URL');
const SB_KEY=process.env.SUPABASE_TEST_ANON_KEY||literal('SB_TESTE_KEY');
const projectRef=new URL(SB_URL).hostname.split('.')[0];
if(projectRef!==TEST_REF||SB_URL.includes(PROD_REF))throw Error('Fase 4 bloqueada: use somente '+TEST_REF);
if(!Number.isInteger(RUNS)||RUNS<1||RUNS>20)throw Error('PHASE4_RUNS deve estar entre 1 e 20.');
const F='codlinha,numero_ligacao,nome_ligacao,nome_lig_cresc,via,codempresa,tipo,caracteristica,licitado,cancelado,paralisado,sub_judice,transferido,data_criacao,processo_criacao';
const norm=s=>String(s??'').normalize('NFD').replace(/\p{Diacritic}/gu,'').toLowerCase().trim();
const ilike=s=>encodeURIComponent(String(s??'').replace(/[()*]/g,' '));
const or=(cols,ts)=>'or=('+ts.map(t=>cols.map(c=>c+'.ilike.*'+ilike(t)+'*').join(',')).join(',')+')';
const distinct=rs=>[...new Set(rs.map(r=>r.codlinha).filter(Boolean))];
const meter=()=>({started:performance.now(),calls:[],inflight:0,maxConcurrency:0});
async function req(table,qs,m){const signature=table+'?'+qs,started=performance.now();m.inflight++;m.maxConcurrency=Math.max(m.maxConcurrency,m.inflight);try{const r=await fetch(SB_URL+'/rest/v1/'+table+'?'+qs,{headers:{apikey:SB_KEY,Authorization:'Bearer '+SB_KEY}}),body=await r.text();m.calls.push({table,signature,status:r.status,durationMs:+(performance.now()-started).toFixed(1),payloadBytes:Buffer.byteLength(body)});if(!r.ok)throw Error(table+' HTTP '+r.status+' '+body.slice(0,120));return JSON.parse(body);}finally{m.inflight--;}}
function done(m){const u=new Set(m.calls.map(c=>c.signature));return{requests:m.calls.length,uniqueRequests:u.size,redundantRequests:m.calls.length-u.size,durationMs:+(performance.now()-m.started).toFixed(1),payloadBytes:m.calls.reduce((s,c)=>s+c.payloadBytes,0),maxConcurrency:m.maxConcurrency,errors:m.calls.filter(c=>c.status>=400).length,calls:m.calls};}
async function ibge(c,m){if(c.ibge)return c.ibge;const rs=await req('municipio_teste','select=cod_ibge,nome_municipio,regiao_municipio,regiao_novo&limit=2000',m);c.ibge={};rs.forEach(r=>c.ibge[r.cod_ibge]={nome:r.nome_municipio});return c.ibge;}
async function empresas(c,m){if(!c.empresas)c.empresas=await req('codempresa_teste','select=codempresa,nome_empresa,situacao,cassada,sob_intervencao&limit=2000',m);return c.empresas;}
async function localidades(c,m){if(c.localidades)return c.localidades;const rs=await req('localidades_teste','select=localidade,ordem_importacao&order=ordem_importacao&limit=2000',m),seen=new Set(),out=[];rs.forEach(r=>{const n=String(r.localidade||'').replace(/^"+|"+$/g,'').trim(),k=n.toLowerCase();if(n.length>=3&&k!=='localidade'&&!seen.has(k)){seen.add(k);out.push(n);}});return c.localidades=out.sort((a,b)=>a.localeCompare(b));}
async function terms(term,c,m){const list=await localidades(c,m),nt=norm(term),all=[...(nt?list.filter(n=>norm(n).includes(nt)).slice(0,5):[]),term.trim()],seen=new Set();return all.filter(t=>{const k=t.toLowerCase();if(!t||seen.has(k))return false;seen.add(k);return true;});}
async function munLines(code,c,m,memo){const k=String(code);if(memo?.has(k))return memo.get(k);const p=req('itinerario_teste','cod_municipio_origem=eq.'+encodeURIComponent(code)+'&select=codlinha&limit=30000',m).then(distinct);if(memo)memo.set(k,p);return p;}
const lineRows=(codes,m,limit=300)=>codes.length?req('tabela_vista_teste','codlinha=in.('+codes.map(encodeURIComponent).join(',')+')&select='+F+'&order=nome_ligacao&limit='+limit,m):[];
async function hero(c){const m=meter(),t=ilike('NITERÓI');await req('tabela_vista_teste','or=(nome_ligacao.ilike.*'+t+'*,numero_ligacao.ilike.*'+t+'*,codlinha.ilike.*'+t+'*)&select='+F+'&order=nome_ligacao&limit=40',m);return done(m);}
async function municipality(a,b,c,optimized){const m=meter(),map=await ibge(c,m),find=t=>Object.entries(map).filter(([,v])=>norm(v.nome).includes(norm(t))).map(([k])=>k),memo=new Map(),all=new Set(),pairs=[];for(const ca of find(a).slice(0,5))for(const cb of find(b).slice(0,5)){if(ca===cb)continue;const la=await munLines(ca,c,m,memo),lb=new Set(await munLines(cb,c,m,memo)),both=la.filter(x=>lb.has(x));if(optimized){if(both.length)pairs.push({ca,cb,codes:both.slice(0,200)});}else if(both.length){const rows=await req('itinerario_teste','codlinha=in.('+both.slice(0,200).map(encodeURIComponent).join(',')+')&select=codlinha,cod_municipio_origem,sentido&order=id&limit=30000',m),groups=new Map();rows.forEach(r=>{const k=r.codlinha+'¦'+(r.sentido||'');if(!groups.has(k))groups.set(k,[]);groups.get(k).push(r);});for(const[k,seq]of groups){const ia=seq.findIndex(r=>String(r.cod_municipio_origem)===String(ca)),ib=seq.findIndex(r=>String(r.cod_municipio_origem)===String(cb));if(ia>=0&&ib>=0&&ia<ib)all.add(k.split('¦')[0]);}}}
if(optimized&&pairs.length){const needed=[...new Set(pairs.flatMap(p=>p.codes))],byLine=new Map();for(let i=0;i<needed.length;i+=200){const batch=needed.slice(i,i+200),rows=await req('itinerario_teste','codlinha=in.('+batch.map(encodeURIComponent).join(',')+')&select=codlinha,cod_municipio_origem,sentido&order=id&limit=30000',m);rows.forEach(r=>{const k=String(r.codlinha),s=r.sentido||'';if(!byLine.has(k))byLine.set(k,new Map());if(!byLine.get(k).has(s))byLine.get(k).set(s,[]);byLine.get(k).get(s).push(r);});}for(const p of pairs)for(const code of p.codes){const senses=byLine.get(String(code));if(!senses)continue;for(const seq of senses.values()){const ia=seq.findIndex(r=>String(r.cod_municipio_origem)===String(p.ca)),ib=seq.findIndex(r=>String(r.cod_municipio_origem)===String(p.cb));if(ia>=0&&ib>=0&&ia<ib){all.add(String(code));break;}}}}
await lineRows([...all].slice(0,250),m,250);return done(m);}
async function locality(c){const m=meter(),ts=await terms('Centro',c,m),[base,sec,it,map]=await Promise.all([req('tabela_vista_teste',or(['nome_ligacao','nome_lig_cresc','via'],ts)+'&select='+F+'&order=nome_ligacao&limit=400',m),req('tarifa_atual_teste',or(['nome_ligacao','via'],ts)+'&select=codlinha&limit=3000',m),req('itinerario_teste',or(['nome_logradouro'],ts)+'&select=codlinha&limit=2000',m),ibge(c,m)]),have=new Set(base.map(r=>r.codlinha)),munSet=new Set();let extra=[...new Set([...sec,...it].map(r=>r.codlinha).filter(x=>x&&!have.has(x)))];const codes=Object.entries(map).filter(([,v])=>norm(v.nome).includes(norm('Niterói'))).map(([k])=>k);for(const code of codes.slice(0,5))(await munLines(code,c,m)).forEach(x=>munSet.add(x));let rows=base.filter(r=>munSet.has(r.codlinha));extra=extra.filter(x=>munSet.has(x));if(extra.length)rows=rows.concat(await lineRows(extra.slice(0,250),m,Math.min(250,extra.length)));await empresas(c,m);const bc=distinct(rows).slice(0,600);if(bc.length)await req('tarifa_atual_teste','codlinha=in.('+bc.map(encodeURIComponent).join(',')+')&'+or(['nome_ligacao','nome_ligacao_cresc'],ts)+'&select=codlinha,secao,nome_ligacao,nome_ligacao_cresc,tipo_ligacao,tarifa,situacao&order=codlinha,secao&limit=5000',m);return done(m);}
const median=xs=>[...xs].sort((a,b)=>a-b)[Math.floor((xs.length-1)/2)];
function summary(rs){return{runs:rs.length,requests:{median:median(rs.map(r=>r.requests)),min:Math.min(...rs.map(r=>r.requests)),max:Math.max(...rs.map(r=>r.requests))},durationMedianMs:median(rs.map(r=>r.durationMs)),payloadMedianBytes:median(rs.map(r=>r.payloadBytes)),redundantMedian:median(rs.map(r=>r.redundantRequests)),maxConcurrency:Math.max(...rs.map(r=>r.maxConcurrency)),errors:rs.reduce((s,r)=>s+r.errors,0)};}
async function coldWarm(fn){const cold=[];for(let i=0;i<RUNS;i++)cold.push(await fn({}));const cache={};await fn(cache);const warm=[];for(let i=0;i<RUNS;i++)warm.push(await fn(cache));return{cold:summary(cold),warm:summary(warm)};}
const before={hero:await coldWarm(hero),rioNiteroi:await coldWarm(c=>municipality('Rio de Janeiro','Niterói',c,false)),rioSao:await coldWarm(c=>municipality('Rio','São',c,false)),centroNiteroi:await coldWarm(locality)};
const after={rioNiteroi:await coldWarm(c=>municipality('Rio de Janeiro','Niterói',c,true)),rioSao:await coldWarm(c=>municipality('Rio','São',c,true))};
const pct=(a,b)=>+((b-a)/a*100).toFixed(1),comparison=Object.fromEntries(['rioNiteroi','rioSao'].map(n=>[n,Object.fromEntries(['cold','warm'].map(t=>[t,{requestsPct:pct(before[n][t].requests.median,after[n][t].requests.median),durationPct:pct(before[n][t].durationMedianMs,after[n][t].durationMedianMs),payloadPct:pct(before[n][t].payloadMedianBytes,after[n][t].payloadMedianBytes)}]))]));
process.stdout.write(JSON.stringify({schemaVersion:1,measuredAt:new Date().toISOString(),target:{projectRef,environment:'teste'},runsPerTemperature:RUNS,before,after,comparison},null,2)+'\n');
